server:
  port: 8081
  servlet:
    context-path: '/api/'
spring:
  application:
    name: cadastro
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  #  properties:
  #    hibernate:
  #      dialect: org.hibernate.dialect.PostgresDialect

api:
  security:
    issuer: "Cadastro Empresa"
    token:
      secret: ${JWT_SECRET:12345678}