services:
  postgres-db:
    image: postgres:16.2
    restart: always
    container_name: cadastro_db
    network_mode: bridge
    ports:
      - '5432:5432'
    environment:
      - "POSTGRES_USER=myuser"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_DB=cadastro_db"